In [45]:
import pandas as pd

hour_cols = [f'Hour {i}' for i in range(1, 25)]

dtype_map = {col: str for col in ['Delivery Date', 'Generator', 'Fuel Type', 'Measurement']}
dtype_map.update({col: float for col in hour_cols})


df = pd.read_csv("../data/PUB_GenOutputCapabilityMonth_202601.csv",
    dtype=dtype_map,
    parse_dates=['Delivery Date'],
    na_values=[' ']
)

df.columns.tolist()

['Delivery Date',
 'Generator',
 'Fuel Type',
 'Measurement',
 'Hour 1',
 'Hour 2',
 'Hour 3',
 'Hour 4',
 'Hour 5',
 'Hour 6',
 'Hour 7',
 'Hour 8',
 'Hour 9',
 'Hour 10',
 'Hour 11',
 'Hour 12',
 'Hour 13',
 'Hour 14',
 'Hour 15',
 'Hour 16',
 'Hour 17',
 'Hour 18',
 'Hour 19',
 'Hour 20',
 'Hour 21',
 'Hour 22',
 'Hour 23',
 'Hour 24']

In [46]:
df.head()

,Delivery Date,Generator,Fuel Type,Measurement,Hour 1,Hour 2,Hour 3,Hour 4,Hour 5,Hour 6,...,Hour 15,Hour 16,Hour 17,Hour 18,Hour 19,Hour 20,Hour 21,Hour 22,Hour 23,Hour 24
0,2026-01-01,ABKENORA,HYDRO,Capability,11.0,11.0,11.0,11.0,11.0,11.0,...,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0
1,2026-01-01,ABKENORA,HYDRO,Output,12.0,12.0,12.0,12.0,12.0,12.0,...,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
2,2026-01-01,ADELAIDE,WIND,Available Capacity,60.0,60.0,60.0,60.0,60.0,60.0,...,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0
3,2026-01-01,ADELAIDE,WIND,Forecast,59.0,58.0,58.0,58.0,58.0,57.0,...,32.0,32.0,17.0,9.0,11.0,17.0,23.0,34.0,29.0,31.0
4,2026-01-01,ADELAIDE,WIND,Output,59.0,59.0,59.0,59.0,59.0,57.0,...,32.0,32.0,16.0,8.0,12.0,18.0,25.0,36.0,28.0,33.0

In [47]:
df.dtypes

Delivery Date    datetime64[us]
Generator                   str
Fuel Type                   str
Measurement                 str
Hour 1                  float64
Hour 2                  float64
Hour 3                  float64
Hour 4                  float64
Hour 5                  float64
Hour 6                  float64
Hour 7                  float64
Hour 8                  float64
Hour 9                  float64
Hour 10                 float64
Hour 11                 float64
Hour 12                 float64
Hour 13                 float64
Hour 14                 float64
Hour 15                 float64
Hour 16                 float64
Hour 17                 float64
Hour 18                 float64
Hour 19                 float64
Hour 20                 float64
Hour 21                 float64
Hour 22                 float64
Hour 23                 float64
Hour 24                 float64
dtype: object

In [48]:
k2 = df[df['Generator'] == 'K2WIND'].copy()
k2_output = k2[k2['Measurement'] == 'Output'].copy()

In [49]:
k2['Measurement'].unique()

<StringArray>
['Available Capacity', 'Forecast', 'Output']
Length: 3, dtype: str

In [50]:
k2_output.head()

,Delivery Date,Generator,Fuel Type,Measurement,Hour 1,Hour 2,Hour 3,Hour 4,Hour 5,Hour 6,...,Hour 15,Hour 16,Hour 17,Hour 18,Hour 19,Hour 20,Hour 21,Hour 22,Hour 23,Hour 24
209,2026-01-01,K2WIND,WIND,Output,247.0,248.0,246.0,239.0,244.0,238.0,...,236.0,245.0,247.0,247.0,247.0,248.0,248.0,248.0,248.0,246.0
635,2026-01-02,K2WIND,WIND,Output,243.0,244.0,237.0,216.0,228.0,228.0,...,198.0,192.0,145.0,154.0,198.0,200.0,195.0,165.0,116.0,125.0
1061,2026-01-03,K2WIND,WIND,Output,160.0,174.0,170.0,149.0,179.0,210.0,...,58.0,58.0,48.0,59.0,87.0,104.0,132.0,135.0,138.0,107.0
1487,2026-01-04,K2WIND,WIND,Output,105.0,104.0,131.0,117.0,127.0,130.0,...,145.0,88.0,49.0,21.0,4.0,0.0,0.0,8.0,17.0,63.0
1913,2026-01-05,K2WIND,WIND,Output,146.0,121.0,169.0,191.0,239.0,238.0,...,8.0,1.0,0.0,0.0,0.0,0.0,3.0,6.0,15.0,25.0

In [51]:
k2_output['Delivery Date'].min(), k2_output['Delivery Date'].max()

(Timestamp('2026-01-01 00:00:00'), Timestamp('2026-01-31 00:00:00'))