In [10]:
import pandas as pd

hour_cols = [f'Hour {i}' for i in range(1, 25)]

dtype_map = {col: str for col in ['Delivery Date', 'Generator', 'Fuel Type', 'Measurement']}
dtype_map.update({col: float for col in hour_cols})


df_all = pd.read_csv("../data/PUB_GenOutputCapabilityMonth_202601.csv",
    dtype=dtype_map,
    parse_dates=['Delivery Date'],
    na_values=[' ']
)

df_all.columns.tolist()

['Delivery Date',
 'Generator',
 'Fuel Type',
 'Measurement',
 'Hour 1',
 'Hour 2',
 'Hour 3',
 'Hour 4',
 'Hour 5',
 'Hour 6',
 'Hour 7',
 'Hour 8',
 'Hour 9',
 'Hour 10',
 'Hour 11',
 'Hour 12',
 'Hour 13',
 'Hour 14',
 'Hour 15',
 'Hour 16',
 'Hour 17',
 'Hour 18',
 'Hour 19',
 'Hour 20',
 'Hour 21',
 'Hour 22',
 'Hour 23',
 'Hour 24']

In [ ]:
df_all.head()

,Delivery Date,Generator,Fuel Type,Measurement,Hour 1,Hour 2,Hour 3,Hour 4,Hour 5,Hour 6,...,Hour 15,Hour 16,Hour 17,Hour 18,Hour 19,Hour 20,Hour 21,Hour 22,Hour 23,Hour 24
0,2026-01-01,ABKENORA,HYDRO,Capability,11.0,11.0,11.0,11.0,11.0,11.0,...,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0
1,2026-01-01,ABKENORA,HYDRO,Output,12.0,12.0,12.0,12.0,12.0,12.0,...,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
2,2026-01-01,ADELAIDE,WIND,Available Capacity,60.0,60.0,60.0,60.0,60.0,60.0,...,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0
3,2026-01-01,ADELAIDE,WIND,Forecast,59.0,58.0,58.0,58.0,58.0,57.0,...,32.0,32.0,17.0,9.0,11.0,17.0,23.0,34.0,29.0,31.0
4,2026-01-01,ADELAIDE,WIND,Output,59.0,59.0,59.0,59.0,59.0,57.0,...,32.0,32.0,16.0,8.0,12.0,18.0,25.0,36.0,28.0,33.0

:

In [20]:
df = df_all[df_all['Fuel Type'] == 'WIND']

print(df['Generator'].nunique())
print(sorted(df['Generator'].unique()))

45
['ADELAIDE', 'AMARANTH', 'AMHERST ISLAND', 'ARMOW', 'BELLE RIVER', 'BLAKE', 'BORNISH', 'BOW LAKE', 'BOW LAKE 2', 'CEDAR POINT 2', 'COMBER', 'CRYSLER', 'DILLON', 'EAST LAKE', 'ERIEAU', 'GOSFIELDWGS', 'GOSHEN', 'GOULAIS', 'GRAND VALLEY 3', 'GRANDWF', 'GREENWICH', 'HENVEY NORTH', 'HENVEY SOUTH', 'JERICHO', 'K2WIND', 'KINGSBRIDGE', 'LANDON', 'MCLEANSMTNWF-LT.AG_T1', 'NORTH KENT', 'PAROCHES', 'PORT BURWELL', 'PORTALMA-T1', 'PORTALMA-T3', 'PRINCEFARM', 'RAILBEDWF-LT.AG_SR', 'RIPLEY SOUTH', 'ROMNEY', 'SANDUSK-LT.AG_T1', 'SHANNON', 'SPENCE', 'SUMMERHAVEN', 'UNDERWOOD', 'WEST LINCOLN NRWF', 'WOLFE ISLAND', 'ZURICH']

In [12]:
df.head()

,Delivery Date,Generator,Fuel Type,Measurement,Hour 1,Hour 2,Hour 3,Hour 4,Hour 5,Hour 6,...,Hour 15,Hour 16,Hour 17,Hour 18,Hour 19,Hour 20,Hour 21,Hour 22,Hour 23,Hour 24
2,2026-01-01,ADELAIDE,WIND,Available Capacity,60.0,60.0,60.0,60.0,60.0,60.0,...,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0
3,2026-01-01,ADELAIDE,WIND,Forecast,59.0,58.0,58.0,58.0,58.0,57.0,...,32.0,32.0,17.0,9.0,11.0,17.0,23.0,34.0,29.0,31.0
4,2026-01-01,ADELAIDE,WIND,Output,59.0,59.0,59.0,59.0,59.0,57.0,...,32.0,32.0,16.0,8.0,12.0,18.0,25.0,36.0,28.0,33.0
9,2026-01-01,AMARANTH,WIND,Available Capacity,153.0,153.0,153.0,124.0,124.0,124.0,...,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0
10,2026-01-01,AMARANTH,WIND,Forecast,71.0,59.0,75.0,56.0,36.0,37.0,...,77.0,71.0,60.0,51.0,65.0,62.0,61.0,49.0,45.0,38.0

In [15]:
dtype_map = {col: float for col in ['Total Project Capacity (MW)', 'Rotor Diameter (m)', 'Hub Height (m)', 'Latitude', 'Longitude']}
# dtype_map.update({col: float for col in hour_cols})


df_cwtd = pd.read_csv("../data/Wind_Turbine_Database_FGP.csv",
    dtype=dtype_map,
    parse_dates=['Commissioning'],
    na_values=[' ']
)

df_cwtd.columns.tolist()

['Province_Territoire',
 'Province_Territoire.1',
 'Project Name',
 'Total Project Capacity (MW)',
 'Turbine Identifier',
 'Turbine Number',
 'Number of Turbines in Project',
 'Turbine Rated Capacity (kW)',
 'Rotor Diameter (m)',
 'Hub Height (m)',
 'Manufacturer',
 'Model',
 'Commissioning',
 'Latitude',
 'Longitude',
 'Notes']

In [16]:
df_cwtd.head()

,Province_Territoire,Province_Territoire.1,Project Name,Total Project Capacity (MW),Turbine Identifier,Turbine Number,Number of Turbines in Project,Turbine Rated Capacity (kW),Rotor Diameter (m),Hub Height (m),Manufacturer,Model,Commissioning,Latitude,Longitude,Notes
0,Ontario,Ontario,OPG 7 Gomberg,0.0000,OPG1,1,1,0,80.00,78.0,Vestas,V80-1.8,2001,43.812073,-79.073921,"Turbine decommissioned in 2019, original capac..."
1,Ontario,Ontario,Living Labs,0.0104,LVL2,2,3,2.4,3.72,15.2,Southwest Windpower,Skystream 3.7,2012,43.831305,-79.588094,NaN
2,Ontario,Ontario,Living Labs,0.0104,LVL1,1,3,1,2.50,17.4,Bergey,Excel 1-48,2012,43.831699,-79.589118,NaN
3,Ontario,Ontario,Living Labs,0.0104,LVL3,3,3,7,1.93,18.3,Darrieus-Savonius,HiVAWT,2015,43.831306,-79.588087,Vertical Axis Hybrid
4,Ontario,Ontario,Hog-Tied Farms,0.2500,HTF1,1,1,250,30.00,30.0,Wind Energy Solutions,WES 250,2007,43.104582,-81.857571,"250 kW, two-bladed model"

In [22]:
print(df_cwtd['Project Name'].nunique())
print(sorted(df_cwtd['Project Name'].unique()))

100
['Adelaide Wind Energy Centre', 'Amherst Island Wind Project', 'Armow Wind Project', 'Arthur', 'Belle River', 'Bisnett Line (Thames River I)', 'Bluewater Wind Farm', 'Bornish Wind Energy Centre', 'Bow Lake Wind Project', 'CAW Wind Turbine', 'Cedar Point', 'Chatham', 'Clear Creek', 'Comber Wind Farm', 'Conestogo', 'Cruickshank', 'Cultus', 'Dufferin Wind', 'East Durham', 'East Lake St. Clair Wind', 'Erie Shores', 'Erieau Wind', 'Ernestown', 'Exhibition Place Turbine', 'Ferndale', 'Frogmore', 'Front Line (Thames River I)', 'Ganaraska', 'Gesner', 'Gosfield', 'Goshen Wind Energy', 'Goulais Wind Farm', 'Gracey (Thames River II)', 'Grand Bend Wind Farm', 'Grand Renewable Wind', 'Grand Valley', 'Greenwich Renewable Energy Project', 'Grey Highlands Clean Energy', 'Grey Highlands Zero Emissions People', "Gunn's Hill", 'HAF Energy', 'Harrow', 'Henvey Inlet Wind Farm', 'Hog-Tied Farms', 'Huron Wind', 'Jericho', 'K2 Wind Power Facility', 'Kent Breeze Wind Farm', 'Kingsbridge I Wind Power', 'Living Labs', 'Marsh Line (Thames River I)', "McLean's Mountain", 'Melancthon', 'Mohawk', 'Moorefield Wind Project', 'Mother Earth Renewable Energy', 'Napier', 'Nation Rise Wind Farm', 'Naylor (Thames River II)', 'Niagara Region', 'North Kent Wind Farm', 'North Malden (Thames River II)', 'OPG 7 Gomberg', 'Oxley Wind Farm', 'Plateau', 'Pointes Aux Roches', 'Port Albert', 'Port Alma', 'Port Dover and Nanticoke', 'Port Ryerse', 'Prince Wind Energy Project', 'Proof Line', 'Providence Bay', 'Quixote One Wind Energy', 'Raleigh Wind Energy Centre', 'Ravenswood Wind Farm', 'Richardson (Thames River II)', 'Ripley', 'Romney', 'Rosa Flora Greenhouses', 'Settlers Landing', 'Skyway 8', 'Snowy Ridge', 'South Branch Wind Farm', 'South Kent Wind Farm', 'South Side (Thames River II)', 'Springwood', 'St. Columban', 'Sumac Ridge', 'Summerhaven', 'Suncor Adelaide Wind Energy', 'Swanton Line (Thames River I)', 'Talbot', 'Tiverton', 'Underwood Wind Farm', 'Wainfleet', 'Watford Wind Farm', 'Whittington', 'Wolfe Island', 'Zurich']

In [58]:
k2_forecast.head()

,Delivery Date,Generator,Fuel Type,Measurement,Hour 1,Hour 2,Hour 3,Hour 4,Hour 5,Hour 6,...,Hour 15,Hour 16,Hour 17,Hour 18,Hour 19,Hour 20,Hour 21,Hour 22,Hour 23,Hour 24
208,2026-01-01,K2WIND,WIND,Forecast,244.0,247.0,247.0,237.0,244.0,239.0,...,233.0,244.0,246.0,247.0,247.0,248.0,248.0,248.0,247.0,245.0
634,2026-01-02,K2WIND,WIND,Forecast,242.0,243.0,237.0,216.0,227.0,227.0,...,194.0,196.0,147.0,150.0,196.0,199.0,196.0,170.0,117.0,124.0
1060,2026-01-03,K2WIND,WIND,Forecast,157.0,169.0,173.0,148.0,174.0,208.0,...,58.0,58.0,49.0,56.0,84.0,99.0,129.0,133.0,140.0,108.0
1486,2026-01-04,K2WIND,WIND,Forecast,104.0,101.0,127.0,121.0,120.0,130.0,...,146.0,94.0,51.0,22.0,5.0,0.0,0.0,6.0,16.0,54.0
1912,2026-01-05,K2WIND,WIND,Forecast,140.0,124.0,162.0,186.0,237.0,235.0,...,9.0,1.0,0.0,0.0,0.0,0.0,1.0,5.0,12.0,22.0

In [ ]:
k2_output['Delivery Date'].min(), k2_output['Delivery Date'].max()

(Timestamp('2026-01-01 00:00:00'), Timestamp('2026-01-31 00:00:00'))

In [59]:
# Melt all measurements together
k2_all = k2.melt(
    id_vars=['Delivery Date', 'Generator', 'Fuel Type', 'Measurement'],
    value_vars=hour_cols,
    var_name='Hour',
    value_name='MWh'
)

k2_all['Hour'] = k2_all['Hour'].str.extract(r'(\d+)').astype(int)

# Pivot so each measurement is a column
k2_pivot = k2_all.pivot_table(
    index=['Delivery Date', 'Hour'],
    columns='Measurement',
    values='MWh'
).reset_index()

k2_pivot.columns.name = None
k2_pivot.head()

  Delivery Date  Hour  Available Capacity  Forecast  Output
0    2026-01-01     1               270.0     244.0   247.0
1    2026-01-01     2               270.0     247.0   248.0
2    2026-01-01     3               270.0     247.0   246.0
3    2026-01-01     4               270.0     237.0   239.0
4    2026-01-01     5               270.0     244.0   244.0

In [67]:
k2_pivot['forecast_gap'] = k2_pivot['Forecast'] - k2_pivot['Output']

k2_pivot['gap_percent'] = k2_pivot['forecast_gap'] / k2_pivot['Forecast'] * 100

# Summary stats
k2_pivot['gap_percent'].describe()

count    733.000000
mean       0.889553
std       15.429829
min     -200.000000
25%       -1.195219
50%        0.000000
75%        0.649351
max      100.000000
Name: gap_percent, dtype: float64

In [68]:
# Hours where output was significantly below forecast (possible curtailment)
threshold = 10  # MW, adjust based on what you see
k2_pivot[k2_pivot['gap_percent'].abs() > threshold].sort_values('forecast_gap', ascending=False)

,Delivery Date,Hour,Available Capacity,Forecast,Output,forecast_gap,gap_percent
295,2026-01-13,8,270.0,178.0,133.0,45.0,25.280899
293,2026-01-13,6,270.0,99.0,66.0,33.0,33.333333
426,2026-01-18,19,270.0,162.0,139.0,23.0,14.197531
679,2026-01-29,8,270.0,75.0,66.0,9.0,12.000000
214,2026-01-09,23,270.0,65.0,57.0,8.0,12.307692
...,...,...,...,...,...,...,...
360,2026-01-16,1,270.0,42.0,50.0,-8.0,-19.047619
95,2026-01-04,24,270.0,54.0,63.0,-9.0,-16.666667
708,2026-01-30,13,270.0,44.0,54.0,-10.0,-22.727273
614,2026-01-26,15,270.0,36.0,49.0,-13.0,-36.111111
709,2026-01-30,14,270.0,138.0,153.0,-15.0,-10.869565